version: "3.8"
services:
  web-services:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      TZ: "Asia/Jakarta"
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      net-eli-app:

networks:
  net-eli-app:
    driver: bridge
